language: go

go:
 - 1.8
 - 1.9
 - tip

addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide

install:
 - glide install

script:
 - go test $(go list ./... | grep -v /vendor/)